### ISSUE TITLE
关于原始论文定理3.2公式(4)的一个疑问

### ISSUE THREAD

**Issue by RachelTeamo** [zhangq327/U-MAE#2]
您好！最近阅读了您的论文《How Mask Matters: Towards Theoretical Understandings of Masked Autoencoders》，这给了我很大的启发，但是我在读到**定理3.2的公式(4)**时候有一个困惑，h表示的是一个**编码-解码器**结构，那么 $h(x_{1})$ 得到的应该是一个重建图，那么这就是一个矩阵，同理 $h_{g}(x_{2})$ 也应该是一个矩阵，那么两个矩阵相乘得到的还是矩阵，为什么等于后面的的那个tr呢？是不是我对h(x)的输出理解有误呢？期待您的答复！

**Comment by yifeiwang77** [comment]
Here, we let the output of h be flattened into a vector, which makes the dot product of $h(x_1)$ and $h_g(x_2)$ a scalar. Hope it helps!

**Comment by RachelTeamo** [comment]
> OK! Thanks ~
