### ISSUE TITLE
关于公式3.2的疑问

### ISSUE THREAD

**Issue by Z-Diviner** [zhangq327/U-MAE#3]
您好，非常高兴能够读到您这篇文章，但是对于公式3.2中的（4）我有一个疑问，这里的L（asym）根据附录的（推导重建损失与非对称对齐损失）证明来看，此处的X1与X2应该是一一对应的，但是3.2的（4）后面的等于三个矩阵相乘的迹这里引入了Am这个二部图的邻接矩阵，是不是没有对应起来？

**Comment by yifeiwang77** [comment]
This is mathematically equivalent, just written in different forms (probability or matrix). Hope it helps.
