### ISSUE TITLE
why random masking process can be modelled as drawing x1, x2 from a joint distribution

### ISSUE THREAD

**Issue by luoyuchenmlcv** [zhangq327/U-MAE#4]
Thanks for presenting your theoretical insight about MAE!

When reading your paper, I found a key problem that hinders me from understanding all the theoretical analysis, that is, why generating a random mask M on an image can be modelled as drawing x1, x2 from a joint distribution M(x1,x2|x). If I understand MAE correctly, denote x as the image, we should have x1+x2=x as x1, x2 are complementary view to each other. Therefore, there is no point to model the random masking process as drawing x1, x2 from a joint distribution, because

 M(x1 = x*m , x2 = x*(1-m)|x) = M(x1 = x*m|x) = M(x2 = x*(1-m)|x), elsewhere 0.

And also, x1,x2 should be one-one corresponded to each other, therefore, for any random target view x2, there should only exist a single x1, rather than exist a positive pair (x1, x1^+), such that x1 and x1^+ share x2 as their common target view.

Hence I also believe the set of two views should have |X1| = |X2|, but your paper says if p!=0.5, |X1| != |X2|. 

Could you help me explain them? Thanks!

**Comment by zhangq327** [comment]
Thanks for your careful reading!

A key point to explain the problems is that the different natural images ($\bar{x}$) will generate overlapped masked and unmasked views (e.g., two different cars have the same wheels). To be specific:

1. As the same unmasked view (the wheels) may be corresponded to different masked views in different natural images, we can not simply replace $M(x1,x2|\bar{x})$ with $M(x1|\bar{x})$. We need the joint distribution to describe the relationship between masked and unmasked views.
2. The implicit positive pairs $(x_1,x_1^+)$ may come from different original images when they have a shared overlapped target.
3. As we discuss in Section 4.2, the mask ratio will influence the degree of overlapping. So the number of overlapped masked views and unmasked views is not equal. As a result, $|X_1| \neq |X_2|$.

Hope it helps!

**Comment by xubin04** [comment]
I have the same question. And I am still quite confused by your previous answerCould you provide a more detailed explanation of this question? I would greatly appreciate it.
