### ISSUE TITLE
some more questions for paper understanding

### ISSUE THREAD

**Issue by luoyuchenmlcv** [zhangq327/U-MAE#5]
Thanks for presenting your theoretical insight about MAE!

By following your explaination on #4, an implicit positive pair $(x_1, x_1^+)$ could be semanticlly different, for example $x_1$ is the window of a car and $ x_1^+$ is the wheel of a car. But their complementary view $(x_2, x_2^+)$ should both be describing car, maybe  $x_2$ is largely describing a blue car and   $x_2^+$ is largely describing a yellow car, by this way the MAE model is trying to decode semanticlly similar contents from  $(x_1, x_1^+)$, hence  $(x_1, x_1^+)$ is called a positive pair, is that correct?

Also, could you provide proof for theorem 3.2, how you transform the formula in MAE loss to that dot product lower bound? Thanks!

**MAE loss**
![image](https://github.com/zhangq327/U-MAE/assets/102636806/d6db3557-06d3-40fe-9726-5b68ee44d5f9)

BTW, is your MAE loss formula can be calculated in canonical way as x_1+x_2=x,
$l_{MAE}(h) = \sum_x\sum_{(x_1,x_2)}\|h(x_1)-x_2\|^2$

When assuming $E_x\|h_g(x)-x\|^2 \leq \epsilon$, how do you get the following:
**Theorem 3.2**
![image](https://github.com/zhangq327/U-MAE/assets/102636806/2a315874-6332-489d-a36e-27cbefbf5505)

**Comment by zhangq327** [comment]
1. In Theorem 4.1, we use the labeling error $\alpha$ to calculate the probability that the masking technique changes the labels of images (i.e., the semantics). And we prove that the larger labeling error implies a larger downstream error. BTW, it is worth noting that our analysis focuses on the downstream classification tasks. So I think aligning the yellow car and the blue car will be beneficial on the downstream classification tasks as they both belong to the same class (car).
2. The proof of Theorem 3.2 can be found in Appendix A.1.
3. It is worth noting that $x$ in Assumption 3.1 represents either unmasked data $x_1$ or masked data $x_2$. And $x$ is different from the natural image $\bar{x}$.

Hope it helps!
