### ISSUE TITLE
Questions about augmentation graph

### ISSUE THREAD

**Issue by I-AM-PROTO** [zhangq327/U-MAE#6]
Hi! I was reading your paper, and I'm confused about the point it's making around the implicit positive connections.

In the paper, it claims:

> Consider a pair of 2-hop input neighbors $x_1, x^+_1 \in \mathcal{X}_1$ that share a common complementary target view $x_2 \in \mathcal{X}_2$ (more likely to happen under a larger mask ratio $\rho$), as illustrated in Figure 1(a). By enforcing $x_1, x^+_1$ to reconstruct the same output $x_2$, MAE will implicitly map their features together. In this way, the 2-hop input neighbors serve as positive pairs that will be implicitly aligned as in contrastive learning.

My question is that, if the masking ratio is high, shouldn't it be *less* likely that such thing happens?

In an extreme case where $\rho=0$, no patches will be masked. This means that $x_1$ is simply the original image and $x_2=\mathbf{0}$. According to the quote, MAE is assigning every possible image pair in the dataset as positive when the masking ratio is at its lowest. On the other hand, if $\rho\approx 1$ such that all but one patch is masked, it will become much harder to find two $x_1, x^+_1$ that share the common $x_2$, as it would require the whole image to be almost identical for that to happen.

This is the most interesting and crucial part of the paper, so I would really appreciate any help on understanding this.

Thank you!

**Comment by zhangq327** [comment]
Thanks for careful reading. There are two points that may be helpful!
1. We should note that there exist two implicit augmentation graphs (respectively defined on the masked views and unmasked views). In the augmentation graphs defined on unmasked views, the analysis you proposed is correct. i.e., the higher mask ratio implies fewer connections. While in the augmentations defined on masked views, it is the opposite.
2. We should note that more connections can not lead to better generalization performance. As we analyzed in Section 4, more connections will increase labeling errors and decrease the eigenvalues of the normalized adjacent matrix. There exists a trade-off between them. And the theoretical analysis on the relationship between the mask ratio and the generalization performance is under-explored.


Please contact me if you have any further questions!

**Comment by I-AM-PROTO** [comment]
Thanks for your quick response!

I think I understand what you mean. When two images are in similar context (e.g. same class), they would be largely similar with only small differences in detail. Although it's unlikely for the masked images to have *exactly* the same target under high mask ratio, the targets would still have meaningful semantic similarity and would be assigned as a implicit positive pair. I can see that with the car example in Fig 2-a.

However, I still believe my analysis above was indeed about the augmentation graph on masked views. The masked views $x_1, x_1^+$ are more likely to share the *exact* same unmasked view $x_2$, when mask ratio is (irrationally) low. In other words, it is easier for two images to have a single identical patch (low mask ratio) than to have all same patches but one (high mask ratio). This is a description of the 2-hop connection between two masked views, with the same unmasked view in between.

My thought is that it's not the total number of connections that is important here, as the paper implies (or doesn't explicitly cross out, at least). Rather, it's the number of inter/intra-class connections that we probably want to control. Even though extremely low mask ratio will have a lot of connections, most of them will be inter-class - which is not what we want. And an extremely high mask ratio would have very little connections, let alone useful. I think this aligns with your second point, though I'm not quite familiar with the graph theory behind it.

I'm thankful to have this active discussion, please let me know what you think!

**Comment by zhangq327** [comment]
I think that there exists a point we should note.

When the mask ratio increases, both the numbers of the edges and the nodes in the augmentation graph change. So we should consider the eigenvalues of the normalized adjacent matrix instead of the connections(edges). In fact, we believe that the higher mask ratio implies smaller eigenvalues (both intra-class and inter-class). As a result, there exists a trade-off when we select the mask ratio. To formalize this result, we are going to release a toy model to discuss the relationship between the mask ratio and the eigenvalues in the next version of this paper.

**Comment by I-AM-PROTO** [comment]
I see. I hope my understanding in the first paragraph wasn't too far off from yours (please tell me if it is!).

The eigenvalue hypothesis makes sense; since any pair of images would be hard to connect under extremely high mask ratio. That's interesting!

Looking forward to your next paper. Thanks for your patience.
