### ISSUE TITLE
Can not run the finetune.sh

### ISSUE THREAD

**Issue by yjqqqaq** [zhangq327/U-MAE#7]
What is the "cls_feats" in "engine_finetune.py" ? Seems that this variable is not used in anywhere.

**Comment by zhangq327** [comment]
Thank you for pointing out this bug! I made this mistake when I organized the open-source code. You can delete the codes about "cls_feats" in  "engine_finetune.py"  and I will fix it. If you find any other problems, feel free to contact me in this or other issues.
