### ISSUE TITLE
Could this proposed U-MAE loss be applicable for other classification tasks?

### ISSUE THREAD

**Issue by Lazzzycoding** [zhangq327/U-MAE#8]
Dear authors @yifeiwang77 @YisenWang @zhangq327 

Thanks for your wonderful work!

I have read through this paper, and the see the obvious improvement with U-MAE loss. I wonder to know whether the proposed U-MAE loss is applicable for other classification tasks or segmentation tasks, for example 3D point clouds. Do you think it is transferrable? 

Thanks a lot.

**Comment by zhangq327** [comment]
Thanks for appreciating our work!

As shown in Figure 1(b) and Figure 1(c), the U-MAE loss can effectively address the dimensional feature collapse
issue and obtain representations with more effective dimensions, which is not related to the specific linear evaluation task. So I think the proposed U-MAE loss is transferrable for different tasks.

Hope it helps!

**Comment by Lazzzycoding** [comment]
> Thanks for appreciating our work!
> 
> As shown in Figure 1(b) and Figure 1(c), the U-MAE loss can effectively address the dimensional feature collapse issue and obtain representations with more effective dimensions, which is not related to the specific linear evaluation task. So I think the proposed U-MAE loss is transferrable for different tasks.
> 
> Hope it helps!

Thanks very much for your reply! As mentioned in your paper, you also refer that masking is an important component in MAE, do you have any suggestion papers on masking strategy besides random masking? To better improve the MAE performance. Thanks a lot again.

**Comment by zhangq327** [comment]
I have read some works that proposed different strategies besides random masking, e.g., trying to find the center objects in the images and focus on constructing them (Chen, Haijian, et al. "Improving Masked Autoencoders by Learning Where to Mask." arXiv preprint arXiv:2303.06583 (2023).)

Hope it helps!

**Comment by zhangq327** [comment]
> 
> Thanks very much for your reply! As mentioned in your paper, you also refer that masking is an important component in MAE, do you have any suggestion papers on masking strategy besides random masking? To better improve the MAE performance. Thanks a lot again.

I have read some works that proposed different strategies besides random masking, e.g., trying to find the center objects in the images and focus on reconstructing them (Chen, Haijian, et al. "Improving Masked Autoencoders by Learning Where to Mask." arXiv preprint arXiv:2303.06583 (2023).)

Hope it helps!
